[tool.poetry]
name = "kmd"
version = "0.1.0"
description = ""
authors = ["Joshua Levy <joshua@cal.berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
deepgram-sdk = "^3.2.7"
strif = "^0.2.3"
typer = "^0.12.3"
marko = "^2.0.3"
regex = "^2024.5.15"
openai = "^1.30.1"
cachetools = "^5.3.3"
requests = "^2.31.0"
pydub = "^0.25.1"
yt-dlp = "^2024.4.9"
vimeo-downloader = "^0.4.1"
assertpy = "^1.1"
ruamel-yaml = "^0.18.6"
python-slugify = "^8.0.4"
inflect = "^7.2.1"
justext = "^3.0.1"
lxml-html-clean = "^0.1.1"
cssselect = "^1.2.0"
weasyprint = "^62.1"
jinja2 = "^3.1.4"
textual = "^0.58.1"
textual-dev = "^1.5.1"
lark-parser = "^0.12.0"
xonsh = {extras = ["full"], version = "^0.16.0"}
pygments = "^2.18.0"

humanize = "^4.9.0"
[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kmd = "kmd.main:app"
xonsh_install_kmd = "xonsh_install_kmd:install"
kmdsh = "kmdsh:main"

[tool.black]
line-length = 100

[tool.pytest.ini_options]
python_files = ["*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = [
    "kmd",
    "tests",
]
