[tool.poetry]
name = "kmd"
version = "0.1.0"
description = ""
authors = ["Joshua Levy <joshua@cal.berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
deepgram-sdk = "^3.2.7"
strif = "^0.2.3"
typer = "^0.12.3"
marko = "^2.0.3"
regex = "^2024.4.28"
openai = "^1.25.1"
cachetools = "^5.3.3"
requests = "^2.31.0"
pydub = "^0.25.1"
yt-dlp = "^2024.4.9"
vimeo-downloader = "^0.4.1"
assertpy = "^1.1"
ruamel-yaml = "^0.18.6"
python-slugify = "^8.0.4"
inflect = "^7.2.1"
justext = "^3.0.0"
lxml-html-clean = "^0.1.1"
cssselect = "^1.2.0"
weasyprint = "^62.1"
jinja2 = "^3.1.4"
textual = "^0.58.1"
textual-dev = "^1.5.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kmd = "kmd.main:app"

[tool.black]
line-length = 100
