# Copy this template to secrets.toml and set these values.

# OpenAI API key
secret_openai = "<OpenAI API Key>"

# Anthropic API key
secret_anthropic = "<Anthropic API Key>"

# Deepgram API key
secret_deepgram = "<Deepgram API Key>"

# Groq API key
secret_groq = "<Groq API Key>"