from datetime import datetime
import weasyprint
from typing import Optional
from strif import atomic_output_file
from kmd.config import colors
from kmd.config.settings import APP_NAME
from kmd.web_gen.template_render import render_web_template


def html_to_pdf(
    html_content: str,
    output_file_path: str,
    title: Optional[str] = None,
) -> None:
    """
    Converts an HTML doc to a nicely formatted PDF file.
    """

    today = datetime.now().strftime("%Y-%m-%d")
    footer = f"Generated by {APP_NAME} on {today}"

    title = title or ""

    full_html = render_web_template(
        "base_webpage.template.html",
        {
            "title": title,
            "content": html_content,
            "color_defs": colors.generate_css_variables(),
            "footer": footer,
        },
    )
    # Create PDF.
    weasy_html = weasyprint.HTML(string=full_html)
    with atomic_output_file(output_file_path, make_parents=True) as temp_file_path:
        weasy_html.write_pdf(temp_file_path)
